name: Build

on:
  push:
  pull_request:

jobs:
  # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
  permissions:
    pages: write      # to deploy to Pages
    id-token: write   # to verify the deployment originates from an appropriate source
  # Deploy to the github-pages environment
  environment:
    name: github-pages
    url: ${{ steps.deployment.outputs.page_url }}
  build:
    name: Build
    runs-on: ubuntu-latest
    container: wpilib/roborio-cross-ubuntu:2024-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Grant execute permission
        working-directory: ./Base
        run: chmod +x gradlew
      - name: Build robot code
        working-directory: ./Base
        run: ./gradlew build
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # or specific "vX.X.X" version tag for this action